### ISSUE TITLE
Version info

### ISSUE THREAD

**Issue by liminspace** [mjmlio/mjml#225]
I have installed `npm -g install mjml@2.0.2`
But `mjml -V` display `2.0.0`
Is it OK?

**Comment by lohek** [comment]
Ah yes, `mjml -V` show version of `mjml-core` (https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/index.js#L10) not just `mjml`, we fix that on next release.

**Comment by larswittenberg** [comment]
Is it fixed with todays release?
`npm install -g mjml` and `mjml --version` display `2.0.2` for me.

**Comment by ngarnier** [comment]
We still have some surprising behaviour due to the fact that there are different packages (`mjml`, `mjml-core` and `mjml-cli`). We'll keep the discussion here: https://github.com/mjmlio/mjml/issues/371

Sorry for the issue!
