### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated on node 21

### ISSUE THREAD

**Issue by srghma** [mjmlio/mjml#2843]
**To Reproduce**

```sh
$ node -v
v21.0.0

multiline_string="
<mjml>
  <mj-head>
    <mj-breakpoint width="320px" />
  </mj-head>
  <mj-body>
    <mj-section>
      <mj-column>
        <mj-text>
          Hello World!
        </mj-text>
      </mj-column>
    </mj-section>
  </mj-body>
</mjml>
"

# Echo the multiline string to a file in the temporary directory
echo "$multiline_string" > /tmp/multiline_file.txt

node --trace-deprecation node_modules/.bin/mjml -- /tmp/multiline_file.txt -s
```

```
...compiled output

(node:460032) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:392:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:328:10)
    at loadBuiltinModule (node:internal/modules/helpers:102:7)
    at Module._load (node:internal/modules/cjs/loader:995:17)
    at Module.require (node:internal/modules/cjs/loader:1229:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/srghma/projects/adsfasdf/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)

```

**Expected behavior**
no warning to stderr

**MJML environment (please complete the following information):**
 - OS: Nixos
- mjml-core: 4.15.3
- mjml-cli: 4.15.3

**Comment by iRyusa** [comment]
Looks to be related to web-resource-inliner which is used in Juice. IDK if they gonna fix it on their end ?

**Comment by alfonsrv** [comment]
Unlikely. `web-resource-inliner` (the maintainer of `juice`) is looking for someone to take over their repo (https://github.com/Automattic/juice/issues/399)

I have opened an issue on the repo, but this issue has been around for quite some time now. https://github.com/jrit/web-resource-inliner/issues/84

**Comment by johnwhelchel** [comment]
Anyone know of a workaround for this?

**Comment by iRyusa** [comment]
Not for now, I've opened a PR on web-resource-inliner, let's hope they will be able to merge it :D

**Comment by SimenB** [comment]
^ has been merged and released

**Comment by iRyusa** [comment]
Juice is still using the 6.x version of this so it's still not available yet

**Comment by CarsonF** [comment]
Thank you @iRyusa @jrit!
I opened a PR for Juice: https://github.com/Automattic/juice/pull/497

**Comment by CarsonF** [comment]
Alright @iRyusa on to you

**Comment by iRyusa** [comment]
I should be able to release in the next build of MJML5 where I need to tweak few things in it

**Comment by iRyusa** [comment]
Juice has been updated to v11 on `5.0.0-alpha.6` this should fix it

**Comment by samstickland** [comment]
@iRyusa I still get this error. Using the example in the original post it reports:

```
(node:96250) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:114:7)
    at Function._load (node:internal/modules/cjs/loader:1100:17)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/Users/sam/development/hubbado/hubbado_core/node_modules/node-fetch/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
```

```
mjml-core: 4.15.3
mjml-cli: 4.15.3
```

```
node -v
v22.11.0
```

`yarn outdated` doesn't report anything that looks relevant:

```
@selectize/selectize 0.15.2  exotic exotic dependencies    selectize/selectize.js#e6ca6d3ba8f902c38da157f2caf7962c38e82095
postcss-preset-env   10.1.2  10.1.3 10.1.3 dependencies    https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env#readme
sass                 1.83.0  1.83.1 1.83.1 devDependencies https://github.com/sass/dart-sass
vite                 6.0.5   6.0.7  6.0.7  dependencies    https://vite.dev
vue-i18n             10.0.5  11.0.1 11.0.1 dependencies    https://github.com/intlify/vue-i18n/tree/master/packages/vue-i18n#readme
```

I've tried upgrading the packages too and it hasn't made any difference

**Comment by reyhan-affandie** [comment]
i solve that punycode issues by changing the node version 
from 22.13.1 (LTS) to 20.18.2(LTS) or 18.20.6(LTS)
