### ISSUE TITLE
mj-image encodes href and mj-button doesn't

### ISSUE THREAD

**Issue by deanorhan** [mjmlio/mjml#402]
I'm having an issue with the mj-image href attribute that doesn't occur with the mj-button one. I'm using Freemarker to perform substitutions in the generated HTML but the mj-image component URL encodes the href attribute so the substitution key gets mangled.

I.E. i get & #36;{bobeFormatter.createURL('/')} instead of ${bobeFormatter.createURL('/')}

This only is happening with mj-image and not mj-button however. Is there a chance we could have something to switch off the URL encoding?

**Comment by iRyusa** [comment]
Hi @deanorhan 

Confirmed, but I have no idea how it can happen. Because of how our parser work atm, we have many issue with encoding/decoding some attribute.

**Comment by ngarnier** [comment]
@deanorhan thanks for reporting, it's fixed in MJML v3.3.0 (now in beta).

**Comment by ngarnier** [comment]
MJML v3.3.0 is out, fixing this issue! Thanks again for reporting. 

To install: `npm install mjml`

**Comment by lrae24** [comment]
@ngarnier It seems like this issue is still occurring the $ still gets encoded whether i use the href or the src attributes with the mj-image tag.
