### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, open './'    at Error (native)

### ISSUE THREAD

**Issue by ardani** [mjmlio/mjml#504]
Hi, i very interesting about mjml
i try install mjml latest version from npm and try compile simple code from example mjml
then i got error like this
`Error: EISDIR: illegal operation on a directory, open './'    at Error (native)`

any suggest to solve it ?
thanks

**Comment by iRyusa** [comment]
Hello @ardani , can you provide more informations about it ?

Your OS & Node version, and the cmd you've typed ? Thanks !

**Comment by ardani** [comment]
Hi @iRyusa , thanks for reply, it solved now, only need update nodejs

**Comment by iRyusa** [comment]
:+1: Good to know ! You were on Node 3.X ?

**Comment by michaelhelmick** [comment]
This issue is still relevant.

The documentation (README) says that it requires `node>=4.2.0`.

I had `node==4.7.0` and `node==5.4.0` installed and got the above (and below) error.

```fish
(venv) mikehelmick@local [master] ⚡️  nvm use 4.7.0
Now using node v4.7.0 (npm v2.15.11)
(venv) mikehelmick@local [master] ⚡️
./node_modules/mjml/bin/mjml ./project/templates/email/base.mjml -o ./project/templates/email/base.html
Error: EISDIR: illegal operation on a directory, open './project/templates/email/'
    at Error (native)

(venv) mikehelmick@local [master] ⚡️  nvm use 5.4.0
Now using node v5.4.0 (npm v3.3.12)
(venv) mikehelmick@local [master] ⚡️
./node_modules/mjml/bin/mjml ./project/templates/email/base.mjml -o ./project/templates/email/base.html
Error: EISDIR: illegal operation on a directory, open './project/templates/email/'
    at Error (native)
```

However, `node==6.6.0` gives me no problems.

```fish
(venv) mikehelmick@local [master] ⚡️  nvm use 6.6.0
Now using node v6.6.0 (npm v3.10.3)
./node_modules/mjml/bin/mjml ./project/templates/email/base.mjml -o ./project/templates/email/base.html
```

**Comment by auginator** [comment]
I can confirm that I too received this error when using Node version 5.6.0. I updated to version 6.6.0 and I am g2g!

**Comment by samumist** [comment]
I had the same error using Node version 4.7.3. No problem with Node version 6.9.5.

**Comment by LeonardoMinatiCrispyBacon** [comment]
Same problem here. NodeJS version is 5.6.0

**Comment by iRyusa** [comment]
Hi there as said, please update your node version to the current LTS ( 6.X ) we'll update package definition to reflect this change, unless someone has a fix for older node version.

**Comment by LeonardoMinatiCrispyBacon** [comment]
The same issue occours even using node 6.9.5. 
Updated node and the reinstalled MJML but still having the problem.

**Comment by iRyusa** [comment]
Can you do a `node -v` and provide the full stack trace @LeonardoMinatiCrispyBacon ? I did not have any issue with node 6.X branch & 7.X

**Comment by bhandarims12** [comment]
I've facing the same issue on npm 6.13.1 version, when i upload a CSV file using the multer it's response a error **"EISDIR: illegal operation on a directory, open 'tmp'"**. I can not downgrade my npm version.

**Comment by iRyusa** [comment]
You're on the wrong repo I think
